spring:
  application:
    name: driver
  datasource:
    url: jdbc:postgresql://localhost:5432/driver
    username: csadmin
    password: csadmin123

server:
  port: 8087

management:
  endpoint:
    routes:
      enabled: true
    web:
      exposed:
        included: '*'
